DATASET:
    NAME: "stanford2d3d_mask_pan"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    WORKERS: 12
    FOLD: 1
TRAIN:
    EPOCHS: 150
    BATCH_SIZE: 4
    CROP_SIZE: (1080,1080)
    BASE_SIZE: 1080
    BACKBONE_PRETRAINED_PATH: "pretrained/mit_b2.pth"
    MODEL_SAVE_DIR: 'workdirs/stanford2d3d_pan/Stanford2D3D_Fold_1/'
    APEX: False
TEST:
    BATCH_SIZE: 1
    TEST_MODEL_PATH: "checkpoints/Stanford2D3D_Fold_1/best_model_fold_1.pth"
    CROP_SIZE: (2048,1024)

SOLVER:
    OPTIMIZER: "adamw"
    LR: 0.00008
    OHEM: False
    LOSS_NAME: 'ce'
    OFFSET_LINE_WEIGHT: 0.3
    OFFSET_AXIS_WEIGHT: 0.3
    PER_PIXEL_WEIGHT: 0.3
    PER_PIXEL_NORM: False
MODEL:
    MODEL_NAME: "Trans4PASS"
    BACKBONE: "trans4pass_v2"
    EMB_CHANNELS: 128
    USE_DCN: [True, False, False, False]
    USE_DEDE: [True, True, True, True]

AUG:
    CROP: True
    REPROJECTION: True
    REPROJECT_PADDING: False
    X_MAX: 10
    Y_MAX: 10
    Z_MAX: 360